baseURL = 'https://saikat.vercel.app/'
languageCode = 'en-us'
defaultcontentlanguage = "en"
title = 'Saikat'
theme = "hugo-coder"
paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Saikat Sengupta"
  info = ["Software Engineer", "Open Source Contributor"]
  description = "Saikat's personal blog"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.png"
  since = 2022
  enableTwemoji = true
  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "GitHub"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/saikatsgupta/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/saikatsgupta/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/saikatsengupta/"
[[params.social]]
  name = "StackOverflow"
  icon = "fa fa-stack-overflow fa-2x"
  weight = 4
  url = "https://stackoverflow.com/users/1594823/"
[[params.social]]
  name = "GitLab"
  icon = "fa fa-gitlab fa-2x"
  weight = 5
  url = "https://gitlab.com/saikatsgupta/"  
  
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"  
